### ISSUE TITLE
The previous secret will be overwritten by same ObjectName

### ISSUE THREAD

**Issue by mitsutaka** [hashicorp/secrets-store-csi-driver-provider-vault#44]
Tested revision: 34a978c51db6b048873167c9e2003c145d2f5f23

If the same ObjectName is included in a SecretProviderClass, the previous secret will be overwritten.

```yaml
    objects: |
      array:
        - |
          objectPath: "/secret/foo"
          objectName: "bar"
          objectVersion: ""
        - |
          objectPath: "/secret/foo1"
          objectName: "bar"
          objectVersion: ""
```
Source: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/vault_v1alpha1_secretproviderclass.yaml

I confimed it by running `e2e-vault` of secrets-store-csi-driver.

```shell
$ k exec -it nginx-secrets-store-inline -- ls -l /mnt/secrets-store
total 4
-rw-r--r-- 1 root root 6 Jun 17 05:56 bar

$ k exec -it nginx-secrets-store-inline -- cat /mnt/secrets-store/bar
hello1
```

Ideally, It should support consul template to output in a flexible format like [vault.hashicorp.com/agent-inject-template](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-inject-template) of Agent Sidecar Injector. but as a short-term fix, I suggest using a slash in the ObjectPath as a hyphen and a file name with a combined ObjectName to generate a unique name. For instance. `secret-foo-bar`. or should create directory based on ObjectPath (#39). I will make a PR if it is accepted.
